### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by lemmuh** [Asmod4n/mruby-simplemsgpack#10]
Hi Hendrik,

on my system with:

```
cmake version 3.30.5
gcc version 13.1.0 
```
the compilation fails with the following error:

`i686-w64-mingw32-gcc: error: unrecognized command-line option ‘-rdynamic’`

It seems to me that the compiler does not support the -rdynamic option anymore. 

Do you have any experience what is the right compiler options for my gcc version and where do I have to set a new option (inside CMakeList.txt?) ?

Thanks !

**Comment by Asmod4n** [comment]
Try installing msgpack with development headers. It might work then.

otherwise you have to reach out to the msgpack authors how to build it for your system.

**Comment by lemmuh** [comment]
Thanks !
